### ISSUE TITLE
Pequeno erro no test

### ISSUE THREAD

**Issue by LizzardMedeiros** [tryber/sd-05-project-crush-manager#18]
O teste do primeiro requisito pede a mensagem:
`'A "senha" deve ter pelo menos 6 caracteres'`

Mas no readme pede:
`'O "password" ter pelo menos 6 caracteres'`

**Comment by luiz-avelar** [comment]
Nos testes estão usando "password".

**Comment by Paulo-Dandrea** [comment]
True story.
