### ISSUE TITLE
Validação do token

### ISSUE THREAD

**Issue by luiz-avelar** [tryber/sd-05-project-crush-manager#19]
Estou em dúvida de como deve ser feita a validação do token a partir do requisito 2. 
Esse token a ser validado é o mesmo gerado o requisito 1? 
Ou deve-se apenas checar se o formato de token provido pela requisição é um formato válido?

**Comment by LizzardMedeiros** [comment]
Pelos testes, acho que só precisa ter o tamanho de 16

**Comment by GabrielCoruja** [comment]
@luiz-avelar mesmo ponto que o Lizzard comentou
